### ISSUE TITLE
Add pointer and click listener for every square, b) make square slightly change background color upon hover

### ISSUE THREAD

**Issue by Ivan-Andr** [Ivan-Andr/psychological-test#10]
### User story
As user,
I want to see  every cell of table slightly change background color upon hover

### Tasks
- [ ] add click listener for every cell of table
- [ ] when cell is clicked log in console number and color (1 red, 25 black )
- [ ] make square slightly change background color upon hover, add pointer

### Acceptance criteria
- [ ] click listeners for every cell off table are added (log to console when clicked)
- [ ] every cell slightly changes background color upon hover
