### ISSUE TITLE
Add form to collect user information

### ISSUE THREAD

**Issue by Ivan-Andr** [Ivan-Andr/psychological-test#14]
### User story
As user,
I want to see а button that opens a form. This form collects user information.

### Tasks
- [ ] Create button (for exsample 'Register') on header of page, that opens a window with form
- [ ] Create a modal window to collect some information (first name, last name, birth year, profession)
- [ ] Main part of app (table and ui will be visible after form comletion
- [ ] In this form user can choose number of test table. (finally it will be able 6-8 tables)
- [ ] Create a function, which pushes collected information in object (later it will send to the local storage)

### Acceptance criteria
- [ ] all tasks are comleted
