### ISSUE TITLE
Add js module functionality

### ISSUE THREAD

**Issue by levnikan** [Ivan-Andr/psychological-test#22]
### **User** story
As a developer, 
I want the source code properly split
### Tasks
- [ ] add modules functionality ([Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#applying_the_module_to_your_html))
- [ ] create src folder and Table (inside src) folder and file e.g. table.js where you can put your `generateTable` function and [export](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#exporting_module_features) it
- [ ] [import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#importing_features_into_your_script) the function into your script.js file
### Acceptance criteria
- [ ] everything works as before, but we have a better code splitting
