### ISSUE TITLE
Create button to select language of app and its functional

### ISSUE THREAD

**Issue by Ivan-Andr** [Ivan-Andr/psychological-test#31]
### User story
As user,
I want to change a language of application interface (Russian, Uzbek, English) 

### Tasks
- [ ] Create button with drop down menu to select language of application interface (Russian, Uzbek, English) 
- [ ] when language is changed all user interface elements and information must be in this language 
- [ ] language by default - russian

### Acceptance criteria
- [ ] language drop menu button is created and user can full full translated version of app
