### ISSUE TITLE
Create HTML table with 7x7 squares

### ISSUE THREAD

**Issue by Ivan-Andr** [Ivan-Andr/psychological-test#4]
As user,
I want to see a 7x7 table with optimal size and alignment on webpage.

### **Tasks**
- [ ]  Create 7x7 HTML table with square сells

### **Acceptance criteria**
- [ ]  Size and alignment of table must be good looking for user, it must be on one screen without scrolling

**Comment by Ivan-Andr** [comment]
As user,
I want to see a 7x7 table  with optimal size and alignment on webpage.  

**Tasks**
- [ ] Create 7x7 HTML table with square сells

**Acceptance criteria**
- [ ] Size and alignment of table must be good looking for user, it must be on one screen without scrolling
