### ISSUE TITLE
Populate table with static digits and give them red and black colors

### ISSUE THREAD

**Issue by Ivan-Andr** [Ivan-Andr/psychological-test#5]
### **User** story
As user, 
I want to see table filled with red and black digits in random order
### ****Tasks
- [ ] fill table with 1-25 black digits in random order
- [ ]  fill  remaing table cells with 1-24 red digits in random order
### ****Acceptance criteria
- [ ] table must be filled with 1-25 black and 1-24 red digits mixed in random order
- [ ] digits must be big, well visible and positioned in the middle of every cell
