### ISSUE TITLE
Create buttons: “start a test” and “finish a test”

### ISSUE THREAD

**Issue by Ivan-Andr** [Ivan-Andr/psychological-test#6]
### User story
As user,
I want to see to buttons: “start a test” and “finish a test”.

### Tasks
- [ ] Create buttons: “start a test” and “finish a test”
- [ ] Add pointer for every button
- [ ] add click listener for buttons

### Acceptance criteria
- [ ] two buttons are created
- [ ] we can see message in conslole  ('start' or 'stop') or modal window
