### ISSUE TITLE
Add timer which would start upon clicking “start” button and stops upon clicking “finish” or after 90 sec

### ISSUE THREAD

**Issue by Ivan-Andr** [Ivan-Andr/psychological-test#7]
### User story
As user,
I want to see timer which would start upon clicking “start” button and stops upon clicking “finish” or after 90 sec

### Tasks
- [ ] Create timer under start and finish buton
- [ ] Add logic to timer: start upon clicking “start” button and stops upon clicking “finish” or after 90 sec.

### Acceptance criteria
- [ ] timer created in user inteface area of a page
- [ ] functionality of timer is respond to task
