### ISSUE TITLE
Add button which would open the modal/dialog window with instructions

### ISSUE THREAD

**Issue by Ivan-Andr** [Ivan-Andr/psychological-test#8]
### User story
As user,
I want to see  a button 'Instructions', which open the modal/dialog window with instructions to test

### Tasks
- [ ] Create buttons 'Instrustions' with pointer
- [ ] Click on button must open the modal/dialog window with instructions to test
- [ ] After test begining this button must be unactive

### Acceptance criteria
- [ ] button is created and click on button opens modal window with instructions to test
- [ ] button must be unactive when test begins
